flags: {}

packages:
    - '.'
    - 'statistics'

extra-deps:
    - bioinformatics-toolkit-0.1.0
    - statistics-0.13.2.4
    - bbi-0.1.0
    - samtools-0.2.4.1
    - glasso-0.1.0

resolver: nightly-2015-12-04
